import type { Metadata } from "next";
import {  Inria_Sans } from "next/font/google";
import "./globals.css";


const InriaSans = Inria_Sans({
  variable: "--font-inria-sans",
  subsets: ["latin"],
  weight: ["400", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt_br">
      <body
        className={`${InriaSans.className} antialiased bg-gradient-to-b from-suport to-main h-screen w-screen`}
      >
        {children}
      </body>
    </html>
  );
}
